
name: Build and test

on:
  pull_request:
    branches: [ master, main, release/** ]

  push:
    branches: [ master, main, release/** ]

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK versions
        uses: actions/setup-java@v4
        with:
          java-version: |
            8
            17
            21
          distribution: zulu

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for gradlew
        working-directory: BetterQuestingAPI
        run: chmod +x gradlew

      - name: Setup CI workspace
        working-directory: BetterQuestingAPI
        run: ./gradlew --build-cache --info --stacktrace setupCIWorkspace

      - name: Build and test
        working-directory: BetterQuestingAPI
        run: ./gradlew --build-cache --info --stacktrace test build
